### ISSUE TITLE
Funcionalidade D

### ISSUE THREAD

**Issue by fersasil** [ccuffs/app-cc#18]
Sobre a funcionalidade D:

D) Aba com mensagens diretas, estilo SMS, onde o aluno receberá informações urgentes ou importantes, e.x.: não haverá aula, período de matrícula, etc.

Como ela será implementada? Haverá um feed no site pra que possamos retirar as informações de lá? Vão exibir notificações?

**Comment by Dovyski** [comment]
Essas informações serão buscadas de uma API do próprio app, que será integrada (ou completamente baseada) na API do curso. Em um momento inicial, eu acho que podemos implementar apenas uma tela de visualização de mensagens (estilo o direct do Instagram, por exemplo), usando dados "fake" (um json com uma estrutura inicial).

Não temos a API do curso com essa funcionalidade ainda. Ficou mais claro agora?

**Comment by fersasil** [comment]
Sim, eu entendi, vou tentar implementar isso quando eu tiver um tempo. Teria algum modelo de json com os dados "fake"?
