### ISSUE TITLE
Arquitetura

### ISSUE THREAD

**Issue by EdSabino** [ccuffs/app-cc#2]
Existe alguma arquitetura que sera utilizada? (MVC, BLOC, Uncle bob, etc)

**Comment by Dovyski** [comment]
Não tenho muito conhecimento do que a comunidade Flutter utiliza. Eu acho que BLoC (Business Logic Components) [parece ser um bom caminho](https://medium.com/flutter-community/flutter-app-architecture-101-vanilla-scoped-model-bloc-7eff7b2baf7e).

**Comment by EdSabino** [comment]
Normalmente utilizamos bloc, existem pacotes para auxiliar isso, como o clean architecture, que preve uma variacao do bloc.
Posso startar issues de implementação, e definicao de arquitetura etc?

**Comment by Dovyski** [comment]
Sinta-se mais que convidado para fazer isso 😄

**Comment by EdSabino** [comment]
show
