### ISSUE TITLE
Tela de ajuda

### ISSUE THREAD

**Issue by fersasil** [ccuffs/app-cc#28]
Eu estava pensando em implementar a tela de ajuda de maneira semelhante a ajuda do nubank:

Os dados podem ser retirados de um json online no formato:

``` json
[
  {
    "categoria1": [
      {
        "nome do item que aparece na segunda tela": "texto do item que aparece na terceira tela, talvez possa ser em html"
      },
      {
        "nome do item que aparece na segunda tela": "texto do item que aparece na terceira tela, talvez possa ser em html"
      }
      ...
    ]
  },
  {
    "categoria2": [
      {
        "nome do item que aparece na segunda tela": "texto do item que aparece na terceira tela, talvez possa ser em html"
      },
      {
        "nome do item que aparece na segunda tela": "texto do item que aparece na terceira tela, talvez possa ser em html"
      }
      ...
    ]
  }
]
```

O icone de pesquisa também pode ser implementado.

O chat seria impossível de ser implementado no momento, mas o "email" é possível. Quando alguém aperta lá, o seu cliente de email abre, colocando o email do contato do nubank como destinatário. É possível implementar algo assim com o email da coordenação.

O que acha @Dovyski ?

<img height=500 src=https://user-images.githubusercontent.com/26921536/90206138-50a68500-ddb9-11ea-8479-18aaa65854ae.png />

<img height=500 src=https://user-images.githubusercontent.com/26921536/90206149-58fec000-ddb9-11ea-9ee3-38a2dc051634.png />

<img height=500 src=https://user-images.githubusercontent.com/26921536/90206231-8e0b1280-ddb9-11ea-847b-ea56d4543e84.png />

**Comment by Dovyski** [comment]
Acho ótima essa ideia e uma boa para implementar agora. Para o json proposto, gostaria que a seguinte estrutura fosse usada:

```json
[
    {   
        "category": {
            "id": 1,
            "title": "Parcelar fatura",
            "content": "Veja como parcelar sua fatura.",
        },
        "entries": [
            {"id": 10, "title": "Como funciona a antecipação do parcelamento da fatura?", "content": "A antecipação do parcelamento traz as parcelas ..."},
            {"id": 11, "title": "Qual é a minha taxa de juros?", "content": "A antecipação do parcelamento traz as parcelas ..."}
        ]
    },
    {   
        "category": {
            "id": 2,
            "title": "Limite de crédito",
            "content": "Tire suas dúvidas sobre limites de crédito.",
        },
        "entries": [
            {"id": 12, "title": "...", "content": "..."},
            {"id": 13, "title": "...", "content": "...."}
        ]
    }
]
```

Ela é mais flexível e nos permitirá alterações mais fáceis no futuro. O chat, como você falou, pode ser deixado de fora agora. Implementamos ele em uma oportunidade futura.
