### ISSUE TITLE
Iniciar Projeto

### ISSUE THREAD

**Issue by EdSabino** [ccuffs/app-cc#3]
O projeto deve ser iniciado, criado uma main, startado o app, adicionado o pubspec.yaml, preparar todo o app para rodar.
Adicionar também a estrutura de pastas para implementar a arquitetura bloc, recomendo o pacote clean_architecture(https://pub.dev/packages/flutter_clean_architecture), e que a mesma seja implementada para o padrao uncle bob, adicionar ao README sobre cada uma das pastas e para que serve cada uma, como devem ser usadas.

**Comment by EdSabino** [comment]
Vou utilizar do commit do rapha, e vou utilizar oq ele fez e passar pra arquitetura bloc, vou criar outras issues para irmos levando o projeto com base nelas

**Comment by Dovyski** [comment]
Excelente!

**Comment by EdSabino** [comment]
Visto que isso foi atendido, fecharei essa issue
